ci: Fetch all git history

diff --git a/.github/workflows/release.hotfix.yaml b/.github/workflows/release.hotfix.yaml
--- a/.github/workflows/release.hotfix.yaml
+++ b/.github/workflows/release.hotfix.yaml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       hotfix_branch:
-        description: "Hotfix branch to release from (e.g., release/hotfix/1.2.3)"
+        description: "Hotfix branch to release from (e.g., hotfix/1.2.3)"
         required: true
 
 env:
@@ -24,6 +24,16 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.hotfix_branch }}
+          fetch-depth: 0
+
+      - name: Fetch all tags
+        run: git fetch --tags --force
+
+      - name: Debug Git History
+        run: |
+          git tag
+          git branch -a
+          git rev-parse --verify main || echo "Main branch not found!"
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
@@ -55,7 +65,6 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build and Push Docker Image
-        id: push
         uses: docker/build-push-action@v5
         with:
           context: .
@@ -65,12 +74,3 @@ jobs:
           tags: |
             ${{ env.GHCR_IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
             ${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}
-
-      - name: Deploy the wavv-prod-backend app
-        uses: digitalocean/app_action/deploy@v2
-        env:
-          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
-        with:
-            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
-            app_spec_location: .do/app.prod.yaml
-    
